tasks:
  - name: Starting web app
    init: |
      cd chess
      npm install
      npm start
      
ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-browser
